export const ALL_BMW_PRODUCTS = 'ALL_BMW_PRODUCTS';
export const ALL_BMW_PRODUCTS_SUCCESS = 'ALL_BMW_PRODUCTS_SUCCESS';

export const NFT_TRACK = 'NFT_TRACK';
export const NFT_TRACK_SUCCESS = 'NFT_TRACK_SUCCESS';
export const SET_LOADER = 'SET_LOADER';
